### ISSUE TITLE
About SFT reproduction

### ISSUE THREAD

**Issue by G17-Ki** [yyDing1/GNER#7]
Since you have not released the ckpt (after SFT), I need to verify the results in the paper. Please provide the prompts and hyperparameters in the SFT stage to ensure that I can reproduce the paper results by performing SFT on GNER-LLaMA-7B. Looking forward to your reply soon.

**Comment by yyDing1** [comment]
We have released the SFT reproduction materials [here](https://drive.google.com/drive/folders/1kg7YDRk8jK4_Bo19jJpZtdAQMBoucppW).

Unfortunately, the checkpoint files for the flan-t5-xxl and llama models were lost during transfer due to their large sizes and unstable transmission. We welcome replication efforts, and we also plan to replicate the models ourselves once computational resources become available.

Detailed instructions for replication are thoroughly explained in our paper, with prompts in Section 4.1 and hyperparameters in Appendix B.
